import{ready}from'@emanote/morph';import{message}from'@emanote/i18n';if(typeof HTMLElement!=='undefined'&&HTMLElement.prototype.hasOwnProperty('popover')&&typeof CSS!=='undefined'&&CSS.escape){ready(init);}
const mobileMQL=window.matchMedia('(max-width: 640px)');const POPOVER_CLASS=['fixed z-[9999] m-0 p-0 border-0 bg-transparent','w-max max-w-[min(32rem,calc(100vw-2rem))]','text-[0.85rem] leading-[1.55]','max-sm:top-auto max-sm:left-0 max-sm:right-0 max-sm:bottom-0','max-sm:w-full max-sm:max-w-full',].join(' ');const BODY_CLASS=['relative bg-white dark:bg-gray-900','text-gray-700 dark:text-gray-300','px-[1.125rem] py-[0.875rem]','rounded-lg border border-gray-200 dark:border-gray-700','border-l-4 border-l-primary-500 dark:border-l-primary-400','shadow-xl','[&>:last-child]:mb-0 [&_p]:m-0 [&_p+p]:mt-2','[&>li]:list-none [&>li]:pl-0 [&>li]:ml-0','max-sm:rounded-t-2xl max-sm:rounded-b-none','max-sm:px-5 max-sm:pt-4 max-sm:pb-6','max-sm:max-h-[60vh] max-sm:overflow-y-auto','max-sm:shadow-2xl',].join(' ');const HEADER_CLASS=['text-xs font-semibold uppercase tracking-wider','text-primary-600 dark:text-primary-400','mb-2',].join(' ');let popoverEl=null;let currentRef=null;let topLevelAside=null;function ensurePopover(){if(popoverEl&&popoverEl.isConnected)return popoverEl;popoverEl=document.createElement('div');popoverEl.id='emanote-footnote-popover';popoverEl.setAttribute('popover','auto');popoverEl.className=POPOVER_CLASS;const body=document.createElement('div');body.className=BODY_CLASS;popoverEl.appendChild(body);document.body.appendChild(popoverEl);popoverEl.addEventListener('toggle',(e)=>{if(e.newState==='closed'&&currentRef){currentRef.classList.remove('emanote-footnote-active');currentRef=null;}});return popoverEl;}
function findOwnAside(scope){const root=scope||document;const asides=root.querySelectorAll('aside[data-footnote-list]');for(const aside of asides){if(aside.closest('[data-footnote-scope]')===scope)return aside;}
return null;}
function findTarget(ref){const idx=ref.getAttribute('data-footnote-ref');if(!idx)return null;const scope=ref.closest('[data-footnote-scope]');let aside;if(scope===null){if(!topLevelAside||!topLevelAside.isConnected){topLevelAside=findOwnAside(null);}
aside=topLevelAside;}else{aside=findOwnAside(scope);}
return aside?aside.querySelector('li[data-footnote-id="'+CSS.escape(idx)+'"]'):null;}
function positionPopover(popover,ref){if(mobileMQL.matches){popover.style.top='';popover.style.left='';return;}
const refRect=ref.getBoundingClientRect();const popRect=popover.getBoundingClientRect();const vw=window.innerWidth;const margin=12;let left=refRect.left+refRect.width/2-popRect.width/2;if(left<margin)left=margin;if(left+popRect.width>vw-margin)left=vw-popRect.width-margin;const spaceAbove=refRect.top;let top;if(spaceAbove>popRect.height+margin){top=refRect.top-popRect.height-8;}else{top=refRect.bottom+8;}
if(top<margin)top=margin;popover.style.top=top+'px';popover.style.left=left+'px';}
function openFor(ref,target){const popover=ensurePopover();const body=popover.firstElementChild;body.textContent='';const idx=ref.getAttribute('data-footnote-ref');if(idx){const header=document.createElement('div');header.className=HEADER_CLASS;header.textContent=message('footnoteLabel',{idx},'Footnote {idx}');body.appendChild(header);}
body.appendChild(target.cloneNode(true));try{popover.hidePopover();}catch(_){}
try{popover.showPopover();}catch(err){console.warn('[emanote] footnote popover showPopover failed',err);return;}
if(currentRef&&currentRef!==ref){currentRef.classList.remove('emanote-footnote-active');}
currentRef=ref;ref.classList.add('emanote-footnote-active');requestAnimationFrame(()=>positionPopover(popover,ref));}
function activate(e,sup){const target=findTarget(sup);if(!target)return;e.preventDefault();openFor(sup,target);}
function onClick(e){if(e.defaultPrevented)return;if(e.button!==0||e.ctrlKey||e.metaKey||e.shiftKey||e.altKey)return;const sup=e.target.closest('sup[data-footnote-ref]');if(sup)activate(e,sup);}
function onKeydown(e){if(e.key!=='Enter'&&e.key!==' ')return;const sup=e.target.closest('sup[data-footnote-ref]');if(sup)activate(e,sup);}
let viewportTick=false;function onViewportChange(){if(viewportTick)return;if(!popoverEl||!popoverEl.matches(':popover-open')||!currentRef)return;viewportTick=true;requestAnimationFrame(()=>{viewportTick=false;if(popoverEl&&popoverEl.matches(':popover-open')&&currentRef){positionPopover(popoverEl,currentRef);}});}
function init(){document.addEventListener('click',onClick);document.addEventListener('keydown',onKeydown);window.addEventListener('resize',onViewportChange);window.addEventListener('scroll',onViewportChange,{passive:true});}