import{onElement}from'@emanote/morph';var lastMode=null;var backlinkSeq=0;function rootProperty(name){return getComputedStyle(document.documentElement).getPropertyValue(name).trim();}
function sidenoteMode(){return rootProperty('--sidenote-mode');}
function sidenoteGap(){return parseFloat(rootProperty('--sidenote-gap'))||0;}
function scrollTo(el,block){var still=window.matchMedia('(prefers-reduced-motion: reduce)').matches;el.scrollIntoView({block:block,behavior:still?'auto':'smooth'});}
function flash(el){el.classList.add('sidenote-focused');setTimeout(function(){el.classList.remove('sidenote-focused');},1500);}
function noteFor(ref){var idx=ref.getAttribute('data-footnote-ref');var scope=ref.closest('[data-footnote-scope]')||document;var lists=scope.querySelectorAll('[data-footnote-list]');for(var i=0;i<lists.length;i++){var li=lists[i].querySelector('li[data-footnote-id="'+CSS.escape(idx)+'"]');if(li)return li;}
return null;}
function pairFootnotes(){document.querySelectorAll('sup[data-footnote-ref]').forEach(function(ref){var li=noteFor(ref);if(!li)return;if(!ref.id)ref.id='fnref-'+(++backlinkSeq);li.classList.add('sidenote');li.dataset.footnoteRef=ref.id;if(!ref.dataset.sidenoteBound){ref.dataset.sidenoteBound='1';ref.addEventListener('click',function(e){e.preventDefault();var note=noteFor(ref);if(!note)return;if(sidenoteMode()==='none'){scrollTo(note,'center');flash(note);}else{focusSidenote(note);}});bindHover(ref,li);}
if(!li.dataset.sidenoteBound){li.dataset.sidenoteBound='1';li.addEventListener('click',function(e){if(sidenoteMode()==='none')return;if(e.target.closest('a'))return;var sel=window.getSelection();if(sel&&!sel.isCollapsed)return;focusSidenote(li);});bindHover(li,ref);}
if(!li.querySelector('.footnote-backlink'))addBacklink(li,ref);});}
function bindHover(from,to){from.addEventListener('mouseenter',function(){from.classList.add('sidenote-hover');to.classList.add('sidenote-hover');});from.addEventListener('mouseleave',function(){from.classList.remove('sidenote-hover');to.classList.remove('sidenote-hover');});}
function addBacklink(li,ref){var back=document.createElement('a');back.setAttribute('href',location.pathname+location.search+'#'+ref.id);back.className='footnote-backlink';back.textContent='↩';back.title='Back to reference '+ref.getAttribute('data-footnote-ref');back.addEventListener('click',function(e){e.preventDefault();scrollTo(ref,'center');flash(ref);});li.appendChild(document.createTextNode(' '));li.appendChild(back);}
function collectItems(){var mainEl=document.querySelector('main');if(!mainEl)return null;var mainRect=mainEl.getBoundingClientRect();var items=[];document.querySelectorAll('li.sidenote').forEach(function(note){var ref=document.getElementById(note.dataset.footnoteRef||'');if(!ref)return;var refRect=ref.getBoundingClientRect();items.push({note:note,naturalTop:refRect.top-mainRect.top+mainEl.scrollTop});});items.sort(function(a,b){return a.naturalTop-b.naturalTop;});return items;}
function assignSide(item,rightCursor,leftCursor,dual){var existing=item.note.dataset.side;if(existing)return existing;var side;if(!dual){side='right';}else if(item.naturalTop>=rightCursor){side='right';}else if(item.naturalTop>=leftCursor){side='left';}else{side=rightCursor<=leftCursor?'right':'left';}
item.note.dataset.side=side;item.note.classList.toggle('sidenote-left',side==='left');return side;}
function layoutSidenotes(){var mode=sidenoteMode();if(mode==='none')return;var items=collectItems();if(!items)return;var dual=mode==='dual';if(mode!==lastMode){items.forEach(function(item){delete item.note.dataset.side;item.note.classList.remove('sidenote-left');});lastMode=mode;}
items.forEach(function(item){item.note.style.transition='none';});var gap=sidenoteGap();var rightCursor=-Infinity;var leftCursor=-Infinity;items.forEach(function(item){var side=assignSide(item,rightCursor,leftCursor,dual);var top;if(side==='right'){top=Math.max(item.naturalTop,rightCursor);rightCursor=top+item.note.offsetHeight+gap;}else{top=Math.max(item.naturalTop,leftCursor);leftCursor=top+item.note.offsetHeight+gap;}
item.note.style.top=top+'px';});void document.body.offsetHeight;items.forEach(function(item){item.note.style.transition='';});}
function focusSidenote(pinnedNote){var allItems=collectItems();if(!allItems)return;var side=pinnedNote.dataset.side;var items=allItems.filter(function(i){return i.note.dataset.side===side;});var pinnedIdx=items.findIndex(function(i){return i.note===pinnedNote;});if(pinnedIdx===-1)return;items[pinnedIdx].top=items[pinnedIdx].naturalTop;var gap=sidenoteGap();var cursor=items[pinnedIdx].top+items[pinnedIdx].note.offsetHeight+gap;for(var i=pinnedIdx+1;i<items.length;i++){items[i].top=Math.max(items[i].naturalTop,cursor);cursor=items[i].top+items[i].note.offsetHeight+gap;}
cursor=items[pinnedIdx].top-gap;for(var j=pinnedIdx-1;j>=0;j--){var naturalBottom=items[j].naturalTop+items[j].note.offsetHeight;items[j].top=Math.min(naturalBottom,cursor)-items[j].note.offsetHeight;cursor=items[j].top-gap;}
items.forEach(function(item){item.note.style.top=item.top+'px';});flash(pinnedNote);scrollTo(pinnedNote,'nearest');}
var pending=false;function sync(){if(pending)return;pending=true;requestAnimationFrame(function(){pending=false;pairFootnotes();layoutSidenotes();});}
onElement('sup[data-footnote-ref]',sync);onElement('[data-footnote-list]',sync);window.addEventListener('load',layoutSidenotes);window.addEventListener('resize',layoutSidenotes);if(document.fonts&&document.fonts.ready){document.fonts.ready.then(layoutSidenotes);}