import{onMorph}from'@emanote/morph';if(typeof stork==='undefined'){throw new Error('stork.js (vendor WASM loader at _emanote-static/stork/stork.js) '+'must load before this module. Check stork-search-head.tpl: the '+"vendor <script src> needs to stay in <head>, before base.tpl's "+'<emanoteJsBundle /> splice.',);}
function getBaseUrl(){try{return new URL(document.baseURI).pathname;}catch(e){console.warn('[emanote] stork: document.baseURI is unparseable; '+'falling back to "/" for index + WASM fetches:',e,);return'/';}}
let indexIsStale=false;const MODAL_HIDDEN_CLASS='stork-overflow-hidden-important';function isSearchShown(){return document.body.classList.contains(MODAL_HIDDEN_CLASS);}
function registerIndex(forceOverwrite=false){const indexName='emanote-search';stork.register(indexName,getBaseUrl()+'-/stork.st',forceOverwrite?{forceOverwrite:true}:undefined,);}
function refreshIndex(){if(!indexIsStale)return;console.log('stork: Reloading index');indexIsStale=false;registerIndex(true);}
function toggleSearch(){refreshIndex();const container=document.getElementById('stork-search-container');if(!container)return;container.classList.toggle('hidden');const nowShown=document.body.classList.toggle(MODAL_HIDDEN_CLASS);if(nowShown){document.getElementById('stork-search-input')?.focus();}}
function clearSearch(){document.getElementById('stork-search-container')?.classList.add('hidden');document.body.classList.remove(MODAL_HIDDEN_CLASS);}
function applyStorkTheme(){const wrapper=document.getElementById('stork-wrapper');if(!wrapper)return;const isDark=document.documentElement.classList.contains('dark');wrapper.classList.remove('stork-wrapper-edible','stork-wrapper-edible-dark');wrapper.classList.add(isDark?'stork-wrapper-edible-dark':'stork-wrapper-edible');}
if(document.readyState==='complete'){stork.initialize(getBaseUrl()+'_emanote-static/stork/stork.wasm');registerIndex();}else{window.addEventListener('load',()=>{stork.initialize(getBaseUrl()+'_emanote-static/stork/stork.wasm');registerIndex();});}
document.addEventListener('click',(e)=>{if(e.target.closest('[data-emanote-stork-toggle]')){toggleSearch();}});document.addEventListener('keydown',(e)=>{if(isSearchShown()&&e.key==='Escape'){clearSearch();e.preventDefault();}else if((e.key==='k'||e.key==='K')&&(e.ctrlKey||e.metaKey)){toggleSearch();e.preventDefault();}});new MutationObserver(applyStorkTheme).observe(document.documentElement,{attributes:true,attributeFilter:['class'],});applyStorkTheme();onMorph(()=>{console.log('stork: Marking index as stale');indexIsStale=true;applyStorkTheme();});