import{ready,onMorph}from'@emanote/morph';import{MONTH_LABELS,SIZE_NARROW,SIZE_WIDE,FLYOUT_OUTER,FLYOUT_CARD,FLYOUT_HEADER,createFilledCell,createEmptyCell,formatCellHeader,}from'@emanote/calendar-grid';const ROW_CLASSES='flex items-center gap-1.5';const LABEL_CLASSES='w-7 text-[0.65rem] uppercase tracking-wider text-gray-500 dark:text-gray-400 select-none shrink-0';const YEAR_LABEL_CLASSES='text-xs font-semibold tracking-tight text-gray-700 dark:text-gray-300 mb-1';function parseEntries(listEl){const out=new Map();for(const li of listEl.querySelectorAll('li')){const title=li.dataset.title||'';const url=li.dataset.url||'';const isoDate=li.dataset.isoDate||'';const contextHTML=li.innerHTML.trim();const parts=isoDate.split('-');if(parts.length!==3)continue;const[y,mo,d]=parts;const year=+y,month=+mo,day=+d;if(!Number.isFinite(year)||!Number.isFinite(month)||!Number.isFinite(day))continue;if(!out.has(year))out.set(year,new Map());const yr=out.get(year);if(!yr.has(month))yr.set(month,new Map());yr.get(month).set(day,{url,title,contextHTML});}
return out;}
function buildFlyout(headerText,contextHTML){const flyout=document.createElement('div');flyout.className=FLYOUT_OUTER;const card=document.createElement('div');card.className=FLYOUT_CARD;const header=document.createElement('div');header.className=FLYOUT_HEADER;header.textContent=headerText;card.appendChild(header);if(contextHTML){const body=document.createElement('div');body.innerHTML=contextHTML;card.appendChild(body);}
flyout.appendChild(card);return flyout;}
function renderMonthRow(year,month,dayMap,wide){const row=document.createElement('div');row.className=ROW_CLASSES;const label=document.createElement('span');label.className=LABEL_CLASSES;label.textContent=MONTH_LABELS[month-1];row.appendChild(label);const sizeClass=wide?SIZE_WIDE:SIZE_NARROW;const cells=document.createElement('div');cells.className=wide?'flex flex-1 gap-px':'flex gap-px';for(let day=1;day<=31;day++){const entry=dayMap&&dayMap.get(day);if(entry){cells.appendChild(createFilledCell({url:entry.url,headerText:formatCellHeader(year,month,day,entry.title),sizeClass,flyoutBuilder:(h)=>buildFlyout(h,entry.contextHTML),}));}else{cells.appendChild(createEmptyCell(sizeClass));}}
row.appendChild(cells);return row;}
function renderYear(year,monthMap,wide){const wrapper=document.createElement('div');wrapper.className='mb-3';const label=document.createElement('div');label.className=YEAR_LABEL_CLASSES;label.textContent=String(year);wrapper.appendChild(label);const rows=document.createElement('div');rows.className='space-y-[2px]';for(let month=1;month<=12;month++){rows.appendChild(renderMonthRow(year,month,monthMap.get(month),wide));}
wrapper.appendChild(rows);return wrapper;}
function render(){for(const section of document.querySelectorAll('.emanote-timeline')){const data=section.querySelector('.timeline-data');const target=section.querySelector('.timeline-heatmap');if(!data||!target)continue;const grouped=parseEntries(data);target.textContent='';if(grouped.size===0){section.hidden=true;continue;}
section.hidden=false;const wide=!!section.closest('.emanote-bottom-strip');const years=[...grouped.keys()].sort((a,b)=>b-a);for(const year of years){target.appendChild(renderYear(year,grouped.get(year),wide));}}}
ready(render);onMorph(render);